#!/bin/sh

BUILDROOT=$PWD
SOURCEROOT=$(dirname $(readlink -f $0))

. $SOURCEROOT/config

cd $SOURCEROOT/kernel
make clean
cd $SOURCEROOT/modules
make clean
cd $SOURCEROOT/programs
make clean
cd $SOURCEROOT
rm -rf $SYSROOT
rm -rf $INITRD