

#ifndef _ASM_MBOOT_H
#define _ASM_MBOOT_H

#define MULTIBOOT_HEADER_MAGIC 0x1BADB002
#define MULTIBOOT_HEADER_FLAG_PAGE_ALIGN (1 << 0)
#define MULTIBOOT_HEADER_FLAG_MEMORY_INFO (1 << 1)
#define MULTIBOOT_HEADER_FLAG_VIDEO_INFO (1 << 2)

#define MULTIBOOT_HEADER_FLAGS (MULTIBOOT_HEADER_FLAG_PAGE_ALIGN | MULTIBOOT_HEADER_FLAG_MEMORY_INFO  | MULTIBOOT_HEADER_FLAG_VIDEO_INFO)

.macro MULTIBOOT_HEADER_BLOCK
.section .multiboot, "aw"
.align 4
.4byte MULTIBOOT_HEADER_MAGIC
.4byte MULTIBOOT_HEADER_FLAGS
.4byte -(MULTIBOOT_HEADER_FLAGS+MULTIBOOT_HEADER_MAGIC)

.skip 40, 0

.endm

#endif